CREATE TABLE IF NOT EXISTS users (
 id CHAR(36) PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, name VARCHAR(20) NOT NULL,
 passwordHash VARCHAR(255) NOT NULL, role ENUM('member','admin','superadmin') NOT NULL DEFAULT 'member',
 color VARCHAR(20) NOT NULL DEFAULT '#c16b51', bio VARCHAR(300) NOT NULL DEFAULT '', createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 tokenHash CHAR(64) PRIMARY KEY, userId CHAR(36) NOT NULL, expiresAt DATETIME NOT NULL,
 FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE, INDEX session_expiry (expiresAt)
);
CREATE TABLE IF NOT EXISTS milestones (
 id CHAR(36) PRIMARY KEY, authorId CHAR(36) NOT NULL, title VARCHAR(80) NOT NULL, body TEXT NOT NULL,
 date DATE NOT NULL, kind ENUM('personal','club') NOT NULL, category VARCHAR(20) NOT NULL, image VARCHAR(255) NOT NULL DEFAULT '',
 createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (authorId) REFERENCES users(id), INDEX milestone_date (date,createdAt), INDEX milestone_author (authorId,date)
);
CREATE TABLE IF NOT EXISTS milestone_participants (
 milestoneId CHAR(36) NOT NULL, userId CHAR(36) NOT NULL, PRIMARY KEY(milestoneId,userId),
 FOREIGN KEY (milestoneId) REFERENCES milestones(id) ON DELETE CASCADE, FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS likes (
 milestoneId CHAR(36) NOT NULL, userId CHAR(36) NOT NULL, PRIMARY KEY(milestoneId,userId),
 FOREIGN KEY (milestoneId) REFERENCES milestones(id) ON DELETE CASCADE, FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS events (
 id CHAR(36) PRIMARY KEY, title VARCHAR(80) NOT NULL, date DATE NOT NULL, place VARCHAR(100) NOT NULL,
 brief VARCHAR(160) NOT NULL, body TEXT NOT NULL, image VARCHAR(255) NOT NULL DEFAULT '', category VARCHAR(20) NOT NULL, capacity INT NOT NULL DEFAULT 30,
 createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX event_date (date)
);
CREATE TABLE IF NOT EXISTS event_attendees (
 eventId CHAR(36) NOT NULL, userId CHAR(36) NOT NULL, PRIMARY KEY(eventId,userId),
 FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE, FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS applications (
 id CHAR(36) PRIMARY KEY, nickname VARCHAR(20) NOT NULL, realName VARCHAR(30) NOT NULL,
 studentId VARCHAR(25) NOT NULL UNIQUE, qq VARCHAR(15) NOT NULL, department VARCHAR(30) NOT NULL, note VARCHAR(500) NOT NULL DEFAULT '',
 status ENUM('pending','contacted','accepted') NOT NULL DEFAULT 'pending', createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_logs (
 id INT AUTO_INCREMENT PRIMARY KEY, actor VARCHAR(40) NOT NULL, action VARCHAR(255) NOT NULL, createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
